title: Endpoint Security
email: info@endpoint-sec.com
description: We deliver the ultimate air-gap security for remote endpoints by ensuring data is only decrypted at the userâ€™s eye level.
baseurl: ""
domain: "endpoint-sec.com"
url: "https://www.endpoint-sec.com/"

theme: just-the-docs
logo: assets/logo.png
nav_enabled: false
search_enabled: false
heading_anchors: false

color_scheme: endpoint

callouts_level: quiet
callouts:
  highlight:
    color: endpoint

ga_tracking: G-X4W72FT9JQ
ga_tracking_anonymize_ip: true

# plugins:
#   - jekyll-notion

# notion:
#   pages:
#     - id: 1978879d650180399f7dc3e28da6e35d
